# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmConfigCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_config_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EmConfigHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=40)),
                ('em_ip_address', models.GenericIPAddressField()),
                ('em_first_seen', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmProfileCurrent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_name', models.CharField(max_length=40)),
            ],
        ),
    ]
